CSV 파일을 train, valid 데이터로 나누기 // 이승훈

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import os
import cv2 as cv
import csv
from sklearn import utils
from sklearn.model_selection import train_test_split

print(tf.test.is_built_with_cuda())
print(tf.config.list_physical_devices('GPU'))


os.chdir('./common_file')

loaded_data=np.loadtxt('./emnist-byclass-train.csv', delimiter=",",dtype='uint8')



True
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [2]:
y_train_full,X_train_full=np.split(loaded_data,[1],axis=1)
print(y_train_full)
#X_train_full=np.delete(loaded_data,0,axis=1)
print(X_train_full)


[[35]
 [36]
 [ 6]
 ...
 [ 5]
 [11]
 [22]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [3]:
X_train, X_valid, y_train, y_valid=train_test_split(X_train_full, y_train_full, test_size=0.235, random_state=42)
np.savetxt('./train_data.csv',X_train,fmt='%d',delimiter=',')
np.savetxt('./valid_data.csv',X_valid,fmt='%d',delimiter=',')
np.savetxt('./train_label.csv',y_train,fmt='%d',delimiter=',')
np.savetxt('./valid_label.csv',y_valid,fmt='%d',delimiter=',')

os.chdir('../') #원래 디렉토리로